### ISSUE TITLE
Peperoni texture transparency issue 5.9.0

### ISSUE THREAD

**Issue by BlockAndPixelAge** [Extex101/jelys_pizzaria#12]
With 5.9.0 some items/nodes if placed have no transparency.

By both peperoni when placed, there are now some black spots.

Other Items or nodes from this mod, from the looks of it, don't have these black spots.

Guess something with texture alpha?

**Comment by Extex101** [comment]
Fixed

**Comment by BlockAndPixelAge** [comment]
Thanks.

**Comment by BlockAndPixelAge** [comment]
Thank you.

**Comment by ghost** [comment]
Thank you.
