### ISSUE TITLE
Slab and Stair names, and a question.

### ISSUE THREAD

**Issue by BlockAndPixelAge** [Extex101/jelys_pizzaria#9]
I noticed that the names of the Reinforced Bricks, when Slab or Stairs (normal, Inner and Outer), only the Slab or Stair part of the name is written small.

Example: "Inner Reinforced Brick stair" instead of "Inner Reinforced Brick Stair"

And now a question.
I read a now closed Issue here about dungeon loot, and want to know, if it's possible to unregister the lines 165-217 in the items.lua with an external Mod.

Why asking, well I created a world with the Seed "Jelys_Pizzaria" (without the ""), one time without and one time with Jelys_Pizzaria enabled, and the dungeon chest at "29.2, -27.7, -6.6" has complete different content in there with this Mod enabled.
Before it was only 3 wheat and 6 coal, with mod enabled it's 3 apples, 2 mese, a wood sword and 8 coal, which doesn't sound like adding, but accidentally changing the loot table.

So if there is a way, to unregister with an external Mod, please tell me.

**Comment by Extex101** [comment]
Thanks for pointing out the Stairs/Slabs typo.

The loot table changing is just a side effect of the way dungeon_loot was programmed; there's no real way around it.
I can add a setting to turn off the pizzeria loot, though this will make one of the rare items unobtainable.

**Comment by BlockAndPixelAge** [comment]
@Extex101 
You mean with rare item, the little "easter egg", that I read at the end of the description on ContentDB.

Adding a setting sounds nice too, and because it's only for one thing, disabling the dungeon loot change, it can maybe help me too, in how to add settings, for different things too.
